name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git credentials (23f2004169@ds.study.iitm.ac.in)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "23f2004169@ds.study.iitm.ac.in"

      - name: Pull latest changes
        run: |
          git pull origin main --rebase || true

      - name: Make a daily commit
        run: |
          echo "Daily commit on $(date)" >> daily_log.txt
          git add daily_log.txt
          git commit -m "Automated daily commit - $(date)"
          git push origin main

